.TH CPACKEXAMPLE 1 "2024-12-07" "cpackexample 1.0" "User Commands"
.SH NAME
cpackexample \- A brief description of what the tool does

.SH SYNOPSIS
.B cpackexample
[OPTIONS]

.SH DESCRIPTION
The cpackexample tool is used to demonstrate packaging with CPack.

.SH OPTIONS
-h, --help
Display help information.

.SH AUTHOR
Your Name <email@example.com>
