set(CPACK_PACKAGE_NAME "${PROJECT_NAME}")
set(CPACK_PACKAGE_VENDOR "SSE Student")
set(CPACK_PACKAGE_CONTACT "schitingluo@gmail.com")
set(CPACK_PACKAGE_MAINTAINERS "SchitingLuo")

set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "SSE CPack Exercise")
set(CPACK_PACKAGE_DESCRIPTION "package the code from the CMake exercise with CPack")
set(CPACK_PACKAGE_HOMEPAGE_URL "https://github.com/SchitingLuo/cpack-exercise-wt2425.git")

set(CPACK_GENERATOR "TGZ;DEB")

# set(CPACK_DEBIAN_PACKAGE_DEPENDS "libyaml-cpp0.8, libboost-filesystem-dev, libc6")

set(CPACK_DEBIAN_FILE_NAME DEB-DEFAULT)
set(CPACK_DEBIAN_PACKAGE_SHLIBDEPS YES)
set(CPACK_DEBIAN_PACKAGE_MAINTAINER ${CPACK_PACKAGE_MAINTAINERS})
# set(CPACK_DEBIAN_PACKAGE_DEPENDS "libyaml-cpp")
set(CPACK_STRIP_FILES TRUE)


include(CPack)
