# CPack configuration
set(CPACK_PACKAGE_NAME "cpack-exercise")
set(CPACK_PACKAGE_VERSION "0.1.0")
set(CPACK_PACKAGE_VENDOR "Marcel Wolkober")
set(CPACK_PACKAGE_CONTACT "st163937@stud.uni-stuttgart.de")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "A simple example project using CPack for the SSE Course")
set(CPACK_PACKAGE_MAINTAINERS "Marcel Wolkober ${CPACK_PACKAGE_CONTACT}")
set(CPACK_PACKAGE_HOMEPAGE_URL "https://github.com/MarcelWolkober/cpack-exercise-wt2425")
set(CPACK_GENERATOR "TGZ;DEB")

# Debian packaging section
set(CPACK_DEBIAN_PACKAGE_NAME "cpack-exercise")
set(CPACK_DEBIAN_PACKAGE_VERSION "${CPACK_PACKAGE_VERSION}")
set(CPACK_DEBIAN_PACKAGE_MAINTAINER "${CPACK_PACKAGE_CONTACT}")
set(CPACK_DEBIAN_PACKAGE_DESCRIPTION "${CPACK_PACKAGE_DESCRIPTION_SUMMARY}")
set(CPACK_DEBIAN_PACKAGE_SECTION "devel")
set(CPACK_DEBIAN_PACKAGE_PRIORITY "optional")
set(CPACK_DEBIAN_PACKAGE_DEPENDS "libyaml-cpp0.6, libboost-filesystem1.71.0, libdeal.ii-dev")
set(CPACK_DEBIAN_FILE_NAME "DEB-DEFAULT")
set(CPACK_DEBIAN_PACKAGE_SHLIBDEPS YES)

include(CPack)